site_name: Duon Error
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
  name: duon
repo_url: https://github.com/duon/error
extra:
  project: Error
plugins:
  - search
  - macros:
      module_name: docs/main