site_name: FiveOrbs Error
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
  name: fiveorbs
repo_url: https://github.com/fiveorbs/error
extra:
  project: Error
plugins:
  - search
  - macros:
      module_name: docs/main
